configured_endpoints: 20
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-cc4b7ab95d315a81419fa6bcab19d23efe8da8b55b7a3d83e5e7da81cf82af5a.yml
