configured_endpoints: 32
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-c9aae1f40694834f9fbb7f60d3003f2981f4947fe66e5ef6205f2716a5e7cc2c.yml
