configured_endpoints: 22
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-1f902c0fa4eb487e2352af781ff55e2ae3e064e11f4f72f8a4b96e77102e62da.yml
