configured_endpoints: 22
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-f3bcc92e94f0560423f1bf9d716af4b7f7c7ae7ede5d9c81139523c2fe0e5962.yml
