configured_endpoints: 20
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-fe83da5c0b063c77b23e0d43955068e8e251b4b4c543e35c9aa1d124342bc9aa.yml
