configured_endpoints: 32
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-1935854c5129cdc3971097618a7755cb26cbf8dbc164b8176a860edbe9b57a7e.yml
