configured_endpoints: 28
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-01ef3577de599aed71cacf2c9f8be50c3e4a7b495b5b328dfa5576c2f0e00af3.yml
