configured_endpoints: 23
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-48aeaf2b79fb48dc24bf3c2a3aa92342f5ea10036e6ab32ad3d057b93c1ab163.yml
