configured_endpoints: 33
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-bfbde79ed2a80c3868d28b648e6f534d43d0c816f8fd00ec62f238a512028e42.yml
